apiVersion: apps/v1
kind: Deployment
metadata:
  name: vectorcli
  labels:
    app: vectorcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vectorcli
  template:
    metadata:
      labels:
        app: vectorcli
    spec:
      containers:
        - name: vectorcli
          image: tiago47611/vectorcli
          args: ["Vector1"]