---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tm
  name: tm
spec:
  ports:
    - name: http
      port: 9002
  selector:
    app.kubernetes.io/name: tm
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tm
    app.kubernetes.io/version: "1.0"
  name: tm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tm
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tm
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: tiago47611/tm
          imagePullPolicy: Always
          name: tm
          ports:
            - containerPort: 9002
              name: http
              protocol: TCP

