apiVersion: apps/v1
kind: Deployment
metadata:
  name: tplm
  labels:
    app: tplm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tplm
  template:
    metadata:
      labels:
        app: tplm
    spec:
      containers:
        - name: tplm
          image: tiago47611/tplm