
package isos.tp1.isyiesd.cestc.sertm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import sertmserver.cestc.isyiesd.isos.iesd21.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITransactionManagerTX", targetNamespace = "http://iesd21.isos.isyiesd.cestc.sertmserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITransactionManagerTX {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "tx_rollback")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tx_rollback", targetNamespace = "http://iesd21.isos.isyiesd.cestc.sertmserver", className = "sertmserver.cestc.isyiesd.isos.iesd21.TxRollback")
    @ResponseWrapper(localName = "tx_rollbackResponse", targetNamespace = "http://iesd21.isos.isyiesd.cestc.sertmserver", className = "sertmserver.cestc.isyiesd.isos.iesd21.TxRollbackResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cestc.sertmserver/ITransactionManagerTX/tx_rollbackRequest", output = "http://iesd21.isos.isyiesd.cestc.sertmserver/ITransactionManagerTX/tx_rollbackResponse")
    public boolean txRollback(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod(operationName = "tx_begin")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tx_begin", targetNamespace = "http://iesd21.isos.isyiesd.cestc.sertmserver", className = "sertmserver.cestc.isyiesd.isos.iesd21.TxBegin")
    @ResponseWrapper(localName = "tx_beginResponse", targetNamespace = "http://iesd21.isos.isyiesd.cestc.sertmserver", className = "sertmserver.cestc.isyiesd.isos.iesd21.TxBeginResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cestc.sertmserver/ITransactionManagerTX/tx_beginRequest", output = "http://iesd21.isos.isyiesd.cestc.sertmserver/ITransactionManagerTX/tx_beginResponse")
    public int txBegin();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "tx_commit")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tx_commit", targetNamespace = "http://iesd21.isos.isyiesd.cestc.sertmserver", className = "sertmserver.cestc.isyiesd.isos.iesd21.TxCommit")
    @ResponseWrapper(localName = "tx_commitResponse", targetNamespace = "http://iesd21.isos.isyiesd.cestc.sertmserver", className = "sertmserver.cestc.isyiesd.isos.iesd21.TxCommitResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cestc.sertmserver/ITransactionManagerTX/tx_commitRequest", output = "http://iesd21.isos.isyiesd.cestc.sertmserver/ITransactionManagerTX/tx_commitResponse")
    public boolean txCommit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
