
package isos.tp1.isyiesd.cesvector.servector;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVectorXA", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVectorXA {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "xa_prepare")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "xa_prepare", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "isos.tp1.isyiesd.cesvector.servector.XaPrepare")
    @ResponseWrapper(localName = "xa_prepareResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "isos.tp1.isyiesd.cesvector.servector.XaPrepareResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVectorXA/xa_prepareRequest", output = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVectorXA/xa_prepareResponse")
    public boolean xaPrepare(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "xa_commit")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "xa_commit", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "isos.tp1.isyiesd.cesvector.servector.XaCommit")
    @ResponseWrapper(localName = "xa_commitResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "isos.tp1.isyiesd.cesvector.servector.XaCommitResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVectorXA/xa_commitRequest", output = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVectorXA/xa_commitResponse")
    public boolean xaCommit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "xa_rollback")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "xa_rollback", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "isos.tp1.isyiesd.cesvector.servector.XaRollback")
    @ResponseWrapper(localName = "xa_rollbackResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "isos.tp1.isyiesd.cesvector.servector.XaRollbackResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVectorXA/xa_rollbackRequest", output = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVectorXA/xa_rollbackResponse")
    public boolean xaRollback(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
