
package isos.tp1.isyiesd.cesvector.servector;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VectorXAService", targetNamespace = "http://servector.cesvector.isyiesd.tp1.isos/", wsdlLocation = "http://localhost:2058/VectorXA?wsdl")
public class VectorXAService
    extends Service
{

    private final static URL VECTORXASERVICE_WSDL_LOCATION;
    private final static WebServiceException VECTORXASERVICE_EXCEPTION;
    private final static QName VECTORXASERVICE_QNAME = new QName("http://servector.cesvector.isyiesd.tp1.isos/", "VectorXAService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2058/VectorXA?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VECTORXASERVICE_WSDL_LOCATION = url;
        VECTORXASERVICE_EXCEPTION = e;
    }

    public VectorXAService() {
        super(__getWsdlLocation(), VECTORXASERVICE_QNAME);
    }

    public VectorXAService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VECTORXASERVICE_QNAME, features);
    }

    public VectorXAService(URL wsdlLocation) {
        super(wsdlLocation, VECTORXASERVICE_QNAME);
    }

    public VectorXAService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VECTORXASERVICE_QNAME, features);
    }

    public VectorXAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VectorXAService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IVectorXA
     */
    @WebEndpoint(name = "VectorXAPort")
    public IVectorXA getVectorXAPort() {
        return super.getPort(new QName("http://servector.cesvector.isyiesd.tp1.isos/", "VectorXAPort"), IVectorXA.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns IVectorXA
     */
    @WebEndpoint(name = "VectorXAPort")
    public IVectorXA getVectorXAPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servector.cesvector.isyiesd.tp1.isos/", "VectorXAPort"), IVectorXA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VECTORXASERVICE_EXCEPTION!= null) {
            throw VECTORXASERVICE_EXCEPTION;
        }
        return VECTORXASERVICE_WSDL_LOCATION;
    }

}
