
package isos.tp1.isyiesd.cestc.sertm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransactionManagerAXService", targetNamespace = "http://sertm.cestc.isyiesd.tp1.isos/", wsdlLocation = "http://localhost:2059/TransactionManagerAX?wsdl")
public class TransactionManagerAXService
    extends Service
{

    private final static URL TRANSACTIONMANAGERAXSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSACTIONMANAGERAXSERVICE_EXCEPTION;
    private final static QName TRANSACTIONMANAGERAXSERVICE_QNAME = new QName("http://sertm.cestc.isyiesd.tp1.isos/", "TransactionManagerAXService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2059/TransactionManagerAX?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSACTIONMANAGERAXSERVICE_WSDL_LOCATION = url;
        TRANSACTIONMANAGERAXSERVICE_EXCEPTION = e;
    }

    public TransactionManagerAXService() {
        super(__getWsdlLocation(), TRANSACTIONMANAGERAXSERVICE_QNAME);
    }

    public TransactionManagerAXService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSACTIONMANAGERAXSERVICE_QNAME, features);
    }

    public TransactionManagerAXService(URL wsdlLocation) {
        super(wsdlLocation, TRANSACTIONMANAGERAXSERVICE_QNAME);
    }

    public TransactionManagerAXService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSACTIONMANAGERAXSERVICE_QNAME, features);
    }

    public TransactionManagerAXService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionManagerAXService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITransactionManagerAX
     */
    @WebEndpoint(name = "TransactionManagerAXPort")
    public ITransactionManagerAX getTransactionManagerAXPort() {
        return super.getPort(new QName("http://sertm.cestc.isyiesd.tp1.isos/", "TransactionManagerAXPort"), ITransactionManagerAX.class);
    }

    /**
     * 
     * @param features
     *     A list of {&#064;link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the &lt;code&gt;features&lt;/code&gt; parameter will have their default values.
     * @return
     *     returns ITransactionManagerAX
     */
    @WebEndpoint(name = "TransactionManagerAXPort")
    public ITransactionManagerAX getTransactionManagerAXPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sertm.cestc.isyiesd.tp1.isos/", "TransactionManagerAXPort"), ITransactionManagerAX.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSACTIONMANAGERAXSERVICE_EXCEPTION!= null) {
            throw TRANSACTIONMANAGERAXSERVICE_EXCEPTION;
        }
        return TRANSACTIONMANAGERAXSERVICE_WSDL_LOCATION;
    }

}
