
package isos.tp1.isyiesd.cesvector.servector;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import servectorserver.cesvector.isyiesd.isos.iesd21.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.3-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IVector", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IVector {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "write", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "servectorserver.cesvector.isyiesd.isos.iesd21.Write")
    @ResponseWrapper(localName = "writeResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "servectorserver.cesvector.isyiesd.isos.iesd21.WriteResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVector/writeRequest", output = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVector/writeResponse")
    public void write(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "servectorserver.cesvector.isyiesd.isos.iesd21.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "servectorserver.cesvector.isyiesd.isos.iesd21.ReadResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVector/readRequest", output = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVector/readResponse")
    public int read(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invariantCheck", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "servectorserver.cesvector.isyiesd.isos.iesd21.InvariantCheck")
    @ResponseWrapper(localName = "invariantCheckResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.servectorserver", className = "servectorserver.cesvector.isyiesd.isos.iesd21.InvariantCheckResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVector/invariantCheckRequest", output = "http://iesd21.isos.isyiesd.cesvector.servectorserver/IVector/invariantCheckResponse")
    public String invariantCheck();

}
