apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  selector:
    app.kubernetes.io/name: registry
  ports:
    - name: http
      protocol: TCP
      port: 9000
      nodePort: 30961
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - name: registry
          image: tiago47611/registry
          ports:
            - containerPort: 9000
              protocol: TCP