---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: b8d46e022f5460df168a80928be8e4b7e3fce977
    app.quarkus.io/build-timestamp: 2022-07-02 - 13:04:58 +0000
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/version: "1.0"
  name: registry
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/version: "1.0"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: b8d46e022f5460df168a80928be8e4b7e3fce977
    app.quarkus.io/build-timestamp: 2022-07-02 - 13:04:58 +0000
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/version: "1.0"
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
      app.kubernetes.io/version: "1.0"
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: b8d46e022f5460df168a80928be8e4b7e3fce977
        app.quarkus.io/build-timestamp: 2022-07-02 - 13:04:58 +0000
      labels:
        app.kubernetes.io/name: registry
        app.kubernetes.io/version: "1.0"
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: tiago47611/registry
          imagePullPolicy: Always
          name: registry
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
